project_id = "rpczvawjzjwytveboiqs"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.get-stripe-prices]
verify_jwt = false

[functions.check-business-subscription]
verify_jwt = false

[functions.list-invoices]
verify_jwt = true

[functions.process-checkout-success]
verify_jwt = false

[functions.send-auth-welcome-email]
verify_jwt = false