project_id = "rpczvawjzjwytveboiqs"

[functions.get-stripe-prices]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.list-invoices]
verify_jwt = true
