project_id = "rpczvawjzjwytveboiqs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "https://app.geracardapio.com"
additional_redirect_urls = ["https://app.geracardapio.com/", "https://app.geracardapio.com/reset-password", "https://7fb2c125-715a-40cb-acb8-5b6724f851b8.lovableproject.com/", "https://7fb2c125-715a-40cb-acb8-5b6724f851b8.lovableproject.com/reset-password"]
jwt_expiry = 86400
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true
email_enable_signup = true
email_enable_confirmations = false

[db]
port = 54322

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-stripe-prices]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false