// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpczvawjzjwytveboiqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwY3p2YXdqemp3eXR2ZWJvaXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzE1NDksImV4cCI6MjA2OTgwNzU0OX0.7S9wL62SHrkXmI4QHl3lF7sqvaNGe3iZMstwGito8BA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});