// This file is automatically generated. Do not edit it directly.
// src/integrations/supabase/client.ts
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use as envs do Vite em produção; mantém fallback para seu projeto atual.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? 'https://rpczvawjzjwytveboiqs.supabase.co';
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwY3p2YXdqemp3eXR2ZWJvaXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzE1NDksImV4cCI6MjA2OTgwNzU0OX0.7S9wL62SHrkXmI4QHl3lF7sqvaNGe3iZMstwGito8BA';

// Fail fast: evita cair em /auth/v1 relativo (que devolve index.html)
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  // eslint-disable-next-line no-console
  console.error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY');
  throw new Error('Supabase env vars not set');
}
if (!SUPABASE_URL.startsWith('https://')) {
  throw new Error('VITE_SUPABASE_URL must start with https://');
}

// Cria o client com opções recomendadas para fluxo de recuperação
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true, // necessário p/ processar tokens no hash
  },
});
